### ISSUE TITLE
import template miss value map

### ISSUE THREAD

**Issue by nebulite** [allburov/zabbix-ibm-server-imm2#1]
<img width="739" alt="screen shot 2017-08-18 at 23 43 14" src="https://user-images.githubusercontent.com/10612844/29466966-5f5a7132-8471-11e7-8f27-b6720b71f3be.png">

**Comment by allburov** [comment]
Hi! Thank for feedback :)
xml have **<value_map>** block - https://github.com/allburov/zabbix-ibm-server-imm2/blob/master/Template%20IBM%20-%20IMM2%20SNMP.xml#L743-L765 

But value-map import supported in zabbix 3.0 https://support.zabbix.com/browse/ZBXNEXT-1679 

Please, create value map manually and give me feedback about it
