### ISSUE TITLE
Change public to SNMP_COMMUNITY

### ISSUE THREAD

**Issue by Satei** [allburov/zabbix-ibm-server-imm2#5]
Hello

Can you please change line 247
from:
<key>getFanSpeed.rb[&quot;public&quot;,{#SNMPINDEX},{HOST.CONN}]</key>
to:
<key>getFanSpeed.rb[{$SNMP_COMMUNITY},{#SNMPINDEX},{HOST.CONN}]</key>

Thanks and regards
Bodo

**Comment by allburov** [comment]
Hi! Thank for feedback :)
Can you fork, test and create pull request, please?
