### ISSUE TITLE
Discovery rules

### ISSUE THREAD

**Issue by zhukovd** [allburov/zabbix-ibm-server-imm2#7]
Hello!
I have a problem with discovery rules. Each discovery rules have error "invalid SNMP OID: pairs of macro and OID are expected."
Can you help me to resolve this?
zabbix version 3.4.11
centos 7

**Comment by allburov** [comment]
Hello, i can't :( Haven't any idea about bug, but google get more

**Comment by allburov** [comment]
Hello, I can't :( Haven't any idea about this bug.
Anybody else may be have idea?

**Comment by zhukovd** [comment]
I found same template and script for zabbix 3.0
https://github.com/rmavrichev/zabbix/blob/master/zbx-templates/ZBX_IBM_IMM2.xml
See readme for script.
